# Generated by Django 4.2 on 2026-04-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_globalpreference_alter_pushsubscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalpreference',
            name='last_sent_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
