import os
import django
import random

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'backend.settings')
django.setup()

from tasks.models import Week, Day, Session, Question, InterviewQuestion

# Comprehensive Day-Specific Question Mapping for all 10 Weeks
DAY_CONTENT = {
    # WEEK 1: PYTHON
    "Python Introduction & Basics": {
        "quiz": [
            {"text": "Who developed Python?", "options": ["Denise Ritchie", "Guido van Rossum", "James Gosling", "Bjarne Stroustrup"], "correct": 1},
            {"text": "Python is an ___ language.", "options": ["Interpreted", "Compiled", "Machine", "Assembly"], "correct": 0},
            {"text": "Which of these is used for multi-line comments in Python?", "options": ["//", "#", "''' or \"\"\"", "/* */"], "correct": 2},
            {"text": "What is the standard indentation in Python according to PEP 8?", "options": ["2 spaces", "4 spaces", "8 spaces", "1 tab"], "correct": 1},
            {"text": "Which of these is NOT a valid variable name?", "options": ["_my_var", "my_var1", "1my_var", "my_Var"], "correct": 2},
            {"text": "Which function is used to get the length of a list in Python?", "options": ["count()", "length()", "len()", "size()"], "correct": 2},
            {"text": "What is the default return value of a function that does not return anything?", "options": ["0", "None", "False", "null"], "correct": 1}
        ],
        "interview": [
            {"level": "Junior", "q": "What are the key features of Python?", "a": "High-level, interpreted, dynamically typed, and has a large standard library. It supports multiple programming paradigms.", "type": "Conceptual"},
            {"level": "Mid", "q": "Explain the difference between .py and .pyc files.", "a": ".py files are source code. .pyc files are compiled bytecode generated by the interpreter to speed up subsequent executions.", "type": "Conceptual"}
        ]
    },
    "Data Structures": {
        "quiz": [
            {"text": "Which of these is a mutable data type?", "options": ["Tuple", "String", "List", "Integer"], "correct": 2},
            {"text": "How do you access the last element of a list 'my_list'?", "options": ["my_list[0]", "my_list[-1]", "my_list[len]", "my_list[last]"], "correct": 1},
            {"text": "Which data structure stores unique elements with no fixed order?", "options": ["List", "Set", "Tuple", "Dictionary"], "correct": 1},
            {"text": "What is the complexity of appending an element to a list?", "options": ["O(1)", "O(n)", "O(log n)", "O(n^2)"], "correct": 0},
            {"text": "Dictionary keys must be ___.", "options": ["String", "Integer", "Mutable", "Immutable"], "correct": 3},
            {"text": "Which method is used to remove an item from a set?", "options": ["delete()", "remove()", "pop()", "discard()"], "correct": 1}
        ],
        "interview": [
            {"level": "Junior", "q": "What is slicing in Python lists?", "a": "A way to extract a sub-portion of a list using the syntax list[start:stop:step].", "type": "Conceptual"},
            {"level": "Mid", "q": "When would you use a Tuple instead of a List?", "a": "When you want to ensure data cannot be modified or when using as a dictionary key.", "type": "Scenario"}
        ]
    },
    "Functions & Iterables": {
        "quiz": [
            {"text": "How is a function defined in Python?", "options": ["function name():", "def name():", "void name():", "func name():"], "correct": 1},
            {"text": "What is '*args' used for in a function definition?", "options": ["Passing a dictionary", "Passing a variable number of positional arguments", "Naming a function", "Setting default values"], "correct": 1},
            {"text": "Which keyword is used to create a generator?", "options": ["return", "emit", "yield", "produce"], "correct": 2},
            {"text": "What does a decorator do?", "options": ["Deletes a function", "Modifies behavior of a function without changing its source", "Styles the output", "Speeds up the CPU"], "correct": 1},
            {"text": "A lambda function is also known as an ___ function.", "options": ["Anonymous", "Named", "Static", "Global"], "correct": 0}
        ],
        "interview": [
            {"level": "Mid", "q": "Explain the difference between a Generator and a List.", "a": "Generators are lazy-loaded (yield items one by one), saving memory, while lists are stored entirely in memory.", "type": "Conceptual"},
            {"level": "Senior", "q": "How would you implement a custom decorator that takes arguments?", "a": "You need three layers of nested functions: the outer for arguments, middle for the function, and inner for the implementation.", "type": "Coding"}
        ]
    },
    "Object Oriented Programming (OOP)": {
        "quiz": [
            {"text": "Which of these is NOT a pillar of OOP?", "options": ["Encapsulation", "Inheritance", "Extraction", "Polymorphism"], "correct": 2},
            {"text": "What is 'self' in a Python class method?", "options": ["The class name", "The current instance of the object", "A reserved keyword for safety", "The parent class"], "correct": 1},
            {"text": "How do you call a parent class method from a child class?", "options": ["parent.method()", "this.method()", "super().method()", "base.method()"], "correct": 2},
            {"text": "Which method is used for constructor behavior in Python?", "options": ["__main__", "__init__", "__start__", "__construct__"], "correct": 1},
            {"text": "What is Polymorphism?", "options": ["Having many forms", "Having one form", "Deleting forms", "Hiding forms"], "correct": 0}
        ],
        "interview": [
            {"level": "Mid", "q": "Explain Method Overriding.", "a": "When a subclass provides a specific implementation of a method that is already defined by its superclass.", "type": "Conceptual"},
            {"level": "Senior", "q": "What is Composition over Inheritance?", "a": "Favoring 'has-a' relationships over 'is-a' relationships to increase flexibility and reduce tight coupling.", "type": "Scenario"}
        ]
    },
    "Advanced & Under the Hood": {
        "quiz": [
            {"text": "What does the GIL stand for?", "options": ["Global Internal Loop", "Global Interpreter Lock", "General Instance List", "Generic Interface Layer"], "correct": 1},
            {"text": "___ is used for manual garbage collection.", "options": ["gc module", "mem module", "os module", "del keyword"], "correct": 0},
            {"text": "What is Monkey Patching?", "options": ["A style of coding", "Dynamic replacement of attributes at runtime", "A security vulnerability", "A memory leak"], "correct": 1},
            {"text": "Which of these is used for asynchronous programming in Python?", "options": ["asyncio", "threading", "multiprocessing", "subprocess"], "correct": 0}
        ],
        "interview": [
            {"level": "Senior", "q": "Why is the GIL often considered a disadvantage in Python?", "a": "It prevents multiple native threads from executing Python bytecodes at once, limiting performance on multi-core machines for CPU-bound tasks.", "type": "Conceptual"}
        ]
    },

    # WEEK 2: DJANGO
    "Django Architecture & Setup": {
        "quiz": [
            {"text": "What architecture does Django follow?", "options": ["MVC", "MVT", "MVP", "Microservices"], "correct": 1},
            {"text": "Which command starts the development server?", "options": ["python manage.py start", "python manage.py runserver", "django run", "server start"], "correct": 1},
            {"text": "Where do you define the list of installed apps?", "options": ["models.py", "urls.py", "settings.py", "wsgi.py"], "correct": 2}
        ],
        "interview": [
            {"level": "Junior", "q": "Explain the MVT architecture.", "a": "Model (Data), View (Logic), Template (UI). The user requests a view, the view gets data from the model and renders it via the template.", "type": "Conceptual"}
        ]
    },
    "URL Dispatching & Views": {
        "quiz": [
            {"text": "What is a 'slug' in Django URL configuration?", "options": ["A database field", "A user-friendly URL label", "A type of view", "A security token"], "correct": 1},
            {"text": "Which function is used to include URLs from another app?", "options": ["append()", "map()", "include()", "import_urls()"], "correct": 2},
            {"text": "Which of these is a Class-Based View?", "options": ["ListView", "render()", "HttpResponse", "redirect()"], "correct": 0}
        ],
        "interview": [
            {"level": "Mid", "q": "What is the difference between reverse() and reverse_lazy()?", "a": "reverse() is evaluated immediately, while reverse_lazy() is evaluated when the value is needed, usually for class-level attributes.", "type": "Conceptual"}
        ]
    },
    "Templates & Static Files": {
        "quiz": [
            {"text": "How do you display a variable in a Django template?", "options": ["{% var %}", "{{ var }}", "[[ var ]]", "<%= var %>"], "correct": 1},
            {"text": "Which tag is used for template inheritance?", "options": ["{% include %}", "{% block %}", "{% extends %}", "{% load %}"], "correct": 2},
            {"text": "Where should static files typically be placed in a production setup?", "options": ["Inside the app folder", "In a 'media' folder", "Collected into STATIC_ROOT", "In the database"], "correct": 2}
        ],
        "interview": [
            {"level": "Junior", "q": "How do you load static files in a template?", "a": "Use {% load static %} at the top and then src='{% static 'path/to/file' %}'.", "type": "Conceptual"}
        ]
    },

    # WEEK 3: DRF
    "REST Principles & Setup": {
        "quiz": [
            {"text": "What does REST stand for?", "options": ["Representation State Transfer", "Representational State Transfer", "Rapid Entity State Transfer", "Request Entity State Transfer"], "correct": 1},
            {"text": "Which HTTP method is used for updating a resource COMPLETELY?", "options": ["POST", "PUT", "PATCH", "DELETE"], "correct": 1},
            {"text": "What is the purpose of HTTP Status Code 404?", "options": ["Created", "Unauthorized", "Not Found", "Internal Server Error"], "correct": 2}
        ]
    },
    "Serializers": {
        "quiz": [
            {"text": "What is the primary role of a Serializer in DRF?", "options": ["Saving to DB", "Converting complex data into JSON", "Handling URLs", "Generating Templates"], "correct": 1},
            {"text": "Which serializer field is used for calculating a value on the fly?", "options": ["CharField", "IntegerField", "SerializerMethodField", "ComputedField"], "correct": 2},
            {"text": "Which method in a Serializer handles data validation?", "options": ["clean()", "validate()", "full_clean()", "check()"], "correct": 1}
        ],
        "interview": [
            {"level": "Mid", "q": "What is the difference between ModelSerializer and Serializer?", "a": "ModelSerializer automatically generates fields based on a Model and provides default implementations for create() and update().", "type": "Conceptual"}
        ]
    },

    # WEEK 4: ORM
    "Models & Schema": {
        "quiz": [
            {"text": "Which command creates migration files?", "options": ["python manage.py migrate", "python manage.py makemigrations", "python manage.py create_sql", "python manage.py sync"], "correct": 1},
            {"text": "What does 'null=True' do?", "options": ["Allows empty string in DB", "Allows NULL value in DB", "Makes field optional in forms", "Deletes the field"], "correct": 1},
            {"text": "Which Meta option specifies the table name?", "options": ["db_table", "table_name", "model_table", "name"], "correct": 0}
        ]
    },
    "QuerySet API Basics": {
        "quiz": [
            {"text": "Which method is used to retrieve a single object by unique ID?", "options": ["filter()", "get()", "all()", "exclude()"], "correct": 1},
            {"text": "How do you filter objects where 'age' is greater than 18?", "options": ["filter(age > 18)", "filter(age__gt=18)", "filter(age__greater=18)", "get(age__gt=18)"], "correct": 1},
            {"text": "What does .exists() do?", "options": ["Returns all objects", "Returns a boolean if any record matches", "Checks if DB is online", "Creates a new record"], "correct": 1}
        ]
    },

    # WEEK 5: FASTAPI
    "FastAPI Introduction": {
        "quiz": [
            {"text": "Who created FastAPI?", "options": ["Guido van Rossum", "Sebastian Ramírez", "Andrew Godwin", "Tom Christie"], "correct": 1},
            {"text": "FastAPI is built on top of ___ and Starlette.", "options": ["Django", "Pydantic", "Flask", "Aiohttp"], "correct": 1},
            {"text": "Which server is commonly used to run FastAPI applications?", "options": ["Gunicorn", "Uvicorn", "Apache", "Nginx"], "correct": 1}
        ]
    },
    "Dependency Injection": {
        "quiz": [
            {"text": "Which function is used for dependency injection in FastAPI?", "options": ["Inject()", "Require()", "Depends()", "Use()"], "correct": 2}
        ]
    },

    # WEEK 9: REACT
    "React Fundamentals & JSX": {
        "quiz": [
            {"text": "What is the Virtual DOM?", "options": ["A direct copy of the real DOM", "A lightweight representation of the real DOM in memory", "A browser plugin", "A backend server"], "correct": 1},
            {"text": "How do you pass data from parent to child in React?", "options": ["via State", "via Props", "via Ref", "via Events"], "correct": 1}
        ]
    },
    "Hooks Deep Dive": {
        "quiz": [
            {"text": "Which hook is used for side effects like data fetching?", "options": ["useState", "useEffect", "useContext", "useMemo"], "correct": 1},
            {"text": "What does a dependency array in useEffect do?", "options": ["Lists all variables used", "Controls when the effect re-runs", "Allocates memory", "Optimizes the build"], "correct": 1}
        ]
    },

    # WEEK 10: REDUX
    "Redux Architecture": {
        "quiz": [
            {"text": "What are the three main components of Redux?", "options": ["Model, View, Controller", "Store, Actions, Reducers", "State, Props, Hooks", "Data, Logic, UI"], "correct": 1},
            {"text": "Redux state is ___.", "options": ["Mutable", "Immutable", "Ephemeral", "Static"], "correct": 1}
        ]
    },
    "Redux Toolkit (RTK) Basics": {
        "quiz": [
            {"text": "Which function creates a slice of state in RTK?", "options": ["createSlice", "configureStore", "useDispatch", "useSelector"], "correct": 0}
        ]
    }
}

# Generic fallback questions to ensure all days have content if lookup fails
GENERIC_QUESTIONS = [
    {"text": "Which protocol is the standard for web communication?", "options": ["FTP", "SMTP", "HTTP/HTTPS", "Telnet"], "correct": 2},
    {"text": "What is the most popular version control system?", "options": ["SVN", "Mercurial", "Git", "CVS"], "correct": 2},
    {"text": "What does IDE stand for?", "options": ["Integrated Design Engine", "Integrated Development Environment", "Internal Development Error", "Interface Data Entry"], "correct": 1},
    {"text": "Which company maintains React?", "options": ["Google", "Microsoft", "Meta", "Amazon"], "correct": 2},
    {"text": "What is the package manager for Node.js?", "options": ["pip", "npm", "maven", "gem"], "correct": 1},
    {"text": "Which language is primarily used for frontend development?", "options": ["Python", "JavaScript", "C#", "Go"], "correct": 1},
    {"text": "What does SQL stand for?", "options": ["Simple Query Language", "Structured Query Language", "Sequential Query Language", "Standard Query Language"], "correct": 1}
]

WEEKS_CONFIG = [
    {"id": "W1", "title": "Python", "days": [
        "Python Introduction & Basics", "Data Structures", "Functions & Iterables", "Object Oriented Programming (OOP)", "Advanced & Under the Hood"
    ]},
    {"id": "W2", "title": "Django", "days": [
        "Django Architecture & Setup", "URL Dispatching & Views", "Templates & Static Files", "Django Admin & Security", "Forms & Validation"
    ]},
    {"id": "W3", "title": "DRF", "days": [
        "REST Principles & Setup", "Serializers", "Views in DRF", "Routers & ViewSets", "Authentication & Permissions"
    ]},
    {"id": "W4", "title": "ORM", "days": [
        "Models & Schema", "Model Relationships", "QuerySet API Basics", "Advanced Lookups & Q/F Objects", "Performance & Aggregation"
    ]},
    {"id": "W5", "title": "FastAPI", "days": [
        "FastAPI Introduction", "Path & Query Parameters", "Pydantic Models (Request Body)", "Dependency Injection", "Middleware & Background Tasks"
    ]},
    {"id": "W6", "title": "FastAPI Advanced", "days": [
        "Security & Authentication", "Relational Databases in FastAPI", "Async Databases", "WebSockets", "Testing & Deployment"
    ]},
    {"id": "W7", "title": "AWS Fundamentals", "days": [
        "Cloud Computing & IAM", "EC2 Compute", "S3 Storage", "Databases (RDS & DynamoDB)", "Networking (VPC Basics)"
    ]},
    {"id": "W8", "title": "AWS Advanced", "days": [
        "Serverless (Lambda & API Gateway)", "Containers (ECS & ECR)", "CDN & DNS", "Infrastructure as Code (IaC)", "CI/CD & Monitoring"
    ]},
    {"id": "W9", "title": "React", "days": [
        "React Fundamentals & JSX", "State & Events", "Hooks Deep Dive", "Routing (React Router)", "Context API & Advanced Patterns"
    ]},
    {"id": "W10", "title": "Redux", "days": [
        "Redux Architecture", "Redux Toolkit (RTK) Basics", "Async Redux (Thunks)", "RTK Query", "Full Project Integration"
    ]}
]

def seed():
    # Cleanup
    Week.objects.all().delete()
    Day.objects.all().delete()
    Session.objects.all().delete()
    Question.objects.all().delete()
    InterviewQuestion.objects.all().delete()
    
    print("Starting Database Seeding with Topic-Specific Content...")

    for w_idx, w_info in enumerate(WEEKS_CONFIG):
        week = Week.objects.create(
            week_id=w_info["id"], 
            title=w_info["title"], 
            is_active=(w_info["id"] == "W1")
        )
        
        for d_idx, topic in enumerate(w_info["days"]):
            day = Day.objects.create(
                week=week,
                day_number=d_idx + 1,
                topic=topic,
                category=w_info["title"],
                duration="8h"
            )
            
            # Setup 5 Sessions per day
            for s_idx in range(5):
                Session.objects.create(
                    day=day,
                    time=f"{9 + s_idx}:00 AM",
                    title=f"Session {s_idx + 1} on {topic}",
                    description=f"Deep dive exploration into {topic} - Module {s_idx + 1}."
                )

            # Assign Topic-Specific Quiz Questions
            content = DAY_CONTENT.get(topic, {"quiz": [], "interview": []})
            topic_quiz = content.get("quiz", [])
            
            # Mix topic-specific with some generic ones to fill up to at least 5 questions
            final_quiz_pool = list(topic_quiz)
            generic_sample = list(GENERIC_QUESTIONS)
            random.shuffle(generic_sample)
            
            while len(final_quiz_pool) < 5:
                final_quiz_pool.append(generic_sample.pop())

            # For days that are highly specific, we use more from their pool
            # For the purpose of this seed, we'll try to use up to 8 questions if available
            random.shuffle(final_quiz_pool)
            
            for q_data in final_quiz_pool[:10]: # Max 10 per day
                Question.objects.create(
                    day=day,
                    text=q_data["text"],
                    options=q_data["options"],
                    correct_option_index=q_data["correct"]
                )
            
            # Interview Questions
            interview_pool = content.get("interview", [
                {"level": "Junior", "q": f"Basic concept of {topic}?", "a": f"Core fundamentals of {topic}.", "type": "Conceptual"},
                {"level": "Mid", "q": f"How to implement {topic} effectively?", "a": "Standard industry patterns and best practices.", "type": "Scenario"}
            ])
            for i_data in interview_pool:
                InterviewQuestion.objects.create(
                    day=day,
                    question=i_data["q"],
                    answer=i_data["a"],
                    level=i_data["level"],
                    type=i_data["type"]
                )

    print("Success! Database seeded with high-quality content for all 10 weeks.")

if __name__ == '__main__':
    seed()
